name: Request Deployment

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST "$DEPLOY_HOOK"
    env:
      DEPLOY_HOOK: ${{ secrets.DEPLOY_HOOK }}

  upload_images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cloudinary Upload Images
        uses: typehut/cloudinary-upload-action@main
        with:
          cloud-name: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          api-key: ${{ secrets.CLOUDINARY_API_KEY }}
          api-secret: ${{ secrets.CLOUDINARY_API_SECRET }}
          images: "./public/**/*.{png,jpg,jpeg,webp,gif}"
